version: '3.7'
services:

##Mongo DB for Storage
 mongo_db: 
  image: mongo
  container_name: mongo_db
  hostname: "${MONGO_HOST}"
  ports:
   - 27017:27017
  restart: always
  volumes:
       - mongodata:/data/db

##Spring Boot Service
 api:
  ports:
    - 8443:8443
  env_file:
    - variables.env
  depends_on:
    - mongo_db
    - rediscache
  build: 
   context: .
   dockerfile : Dockerfile
  restart: always

#volumes   
volumes:
  mongodata :
  cache:
    driver : local

#networks:
#  backend:
#    external: true
  
  
  
   
    